sudo: required

services: docker

before_install: 
  - docoker-compose up --build -d

script: 
  - docoker-compose exec --env 'RAILS_ENV=test' web rails db:create
  - docoker-compose exec --env 'RAILS_ENV=test' web rails db:migrate
  - docoker-compose exec --env 'RAILS_ENV=test' web rails test